### ISSUE TITLE
Sony - Playstation Portable (PSN)

### ISSUE THREAD

**Issue by masanasake** [libretro-thumbnails/Sony_-_PlayStation_Portable#71]
A lot of games are recognizing as this (PSN) category now, and I am not a fan of it. Is it possible to edit metadata to just not do this anymore, or does there need to be another folder set up here to add them? I thought it existed before but was removed...

**Comment by RobLoach** [comment]
We follow No-Intro for naming...
https://datomatic.no-intro.org/index.php?page=search&s=91
