### ISSUE TITLE
Refine one PSP game "Named_Boxarts" image

### ISSUE THREAD

**Issue by ChanKaHou** [libretro-thumbnails/Sony_-_PlayStation_Portable#80]
The "Named_Boxarts" image for the PSP game "Tengai Makyou - Daiyon no Mokushiroku (Japan)" is incorrect:
https://github.com/libretro-thumbnails/Sony_-_PlayStation_Portable/blob/master/Named_Boxarts/Tengai%20Makyou%20-%20Daiyon%20no%20Mokushiroku%20(Japan)%20(v1.02).png

Please find the attached image for the correct used :)
![Tengai Makyou - Daiyon no Mokushiroku (Japan)](https://github.com/libretro-thumbnails/Sony_-_PlayStation_Portable/assets/38522240/66c98775-cf29-4148-854f-ece8a9e79f7d)

**Comment by ChanKaHou** [comment]
no reply?

**Comment by RobLoach** [comment]
Thanks for submitting this. Most contributions are done with Pull Requests. If you're unable to submit one, then I'm happy to take it on.

**Comment by ChanKaHou** [comment]
Oh! Please help me to submit this as “Pull Requests”.

**Comment by ChanKaHou** [comment]
> Thanks for submitting this. Most contributions are done with Pull Requests. If you're unable to submit one, then I'm happy to take it on.

please help, thanks.
